project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Car Collion within Montgomery County"
  author:
    - Ethan Olivier (eto2111)
    - Roy Madpis (rmm2286)

  repo-url: https://github.com/roymadpis/Car_Collision_EDAV_Columbia_2023
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


