# Interactive graph

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>D3 Scatter Plot with Lines</title>
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <!-- Add any additional styling if needed -->
    <style>
     body {
            font-family: 'Roboto', sans-serif;
        }
        button {
            margin: 5px;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            cursor: pointer;
        }

        .title {
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .subtitle {
            font-size: 16px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>

<div class="title">Average number of car accidents per day of month over the years</div>
<div class="subtitle">Click on the month buttons to display each one in the plot.
You can also hover on the different points to see the average number of car accidents in those days.</div>

<div id="chart"></div>
<div id="buttons"></div>

<body>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>


<h5>
-------------------------------------------------------------------------
The interactive visualization can help us compare the average number of accidents between the different months. For example if we click on months: February and December, you can see that, on average, most of December days have higher average accidents than February. Moreover you can see a sharp decrease on the 24-25 of December, which is reasonable as this is the Christmas holiday and less people drive in those days.
Moreover, we can see that some months have small variance between the different day values - for example: September, October and May. There are other months, like July, with higher variance in the average number of daily accidents. You can try different combinations of months to derive those interesting insights. </h5>

<h5> Overall, this interactive graph simplifies a crowded graph by reducing visual overload.  </h5>

</html>
