# Resultsnew

```{r}
library(leaflet)
library(leaflet.extras)
library(dplyr)
library(ggplot2)
library(ggmap)
library(lubridate)

data_crash <- readr::read_csv2("data/data_crash.csv")
#data
```


```{r}

#dt_temporal <- data[,]

dt_temporal <- dplyr::select(data,c("Crash_Date_Time","Weather", "Hit_Run",
                       "First_Harmful_Event", "At_Fault"))

# dt_temporal <- left_join(dt_temporal, holiday_data, by = c("Crash_Date" = "date"))
# 
# dt_temporal <- mutate(dt_temporal, is_holiday = ifelse(is.na(is_holiday), "No", is_holiday))



head(dt_temporal)
```


```{r}
#Separate time and Date

dt_temporal$"Crash_Date_Time" <- as.POSIXct(dt_temporal$"Crash_Date_Time", format = "%m/%d/%Y %I:%M:%S %p", tz = "America/New_York")

dt_temporal$Crash_Date <- as.Date(dt_temporal$"Crash_Date_Time", tz = "America/New_York")

#I have a problem with the hours it doesn't show up well
dt_temporal$Crash_Time <- format(dt_temporal$"Crash_Date_Time", "%H:%M:%S")
dt_temporal
#ggplot(dt_temporal, aes(x = as.factor(Crash_week))) +
       #stat_count() +
       #labs(title='Number of car crash per weeks')

```



### Preprocessing for the df_temporal
```{r}
### add some "date slicers" columns
dt_temporal$Week_day <- weekdays(dt_temporal$Crash_Date)
dt_temporal$Month <-  months(dt_temporal$Crash_Date)
dt_temporal$Year <-  year(dt_temporal$Crash_Date)
dt_temporal$first_day_of_month <- as.Date(format(dt_temporal$Crash_Date, "%Y-%m-01"))

library(hms)
dt_temporal$Crash_Time <- as_hms(dt_temporal$Crash_Time)
dt_temporal$Crash_Hour <- hour(dt_temporal$Crash_Time) #Crash hour


### Transform some colkumns to factors
dt_temporal <- mutate(dt_temporal, Week_day = factor(Week_day,
                                             levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")))

dt_temporal$Month <- factor(dt_temporal$Month, 
                          levels = c("January", "February", "March", "April", "May", "June","July", "August", "September", "October", "November", "December"),)

### arrange the data by date
dt_temporal <- dt_temporal |> arrange(Crash_Date)

dt_temporal_month <- dt_temporal |> group_by(Month, first_day_of_month, Week_day) |> summarise(total_accidents = n())


dt_temporal_Year_month <- dt_temporal |> group_by(Year, Month, first_day_of_month, Week_day) |> summarise(total_accidents = n())


### create a ts object
first_date_in_data <- min(dt_temporal$first_day_of_month)
last_date_in_data <- max(dt_temporal$first_day_of_month)
```
